-- Eliminar a tabela de itens da venda (tabela dependente)
DROP TABLE IF EXISTS item_venda;

-- Eliminar a tabela de vendas
DROP TABLE IF EXISTS venda;

-- Eliminar a tabela de estoque
DROP TABLE IF EXISTS estoque;

-- Eliminar a tabela de produtos
DROP TABLE IF EXISTS produto;

-- Eliminar a tabela de categorias de produto
DROP TABLE IF EXISTS categoria;

-- Eliminar a tabela de promoções
DROP TABLE IF EXISTS promocao;

-- Eliminar a tabela de fornecedores
DROP TABLE IF EXISTS fornecedor;

-- Eliminar a tabela de clientes
DROP TABLE IF EXISTS cliente;

-- Eliminar a tabela de funcionários
DROP TABLE IF EXISTS funcionario;